/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ilzcjsckmyrwlxgnnkkp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsemNqc2NrbXlyd2x4Z25ua2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTM3MDIsImV4cCI6MjA3MzE4OTcwMn0.BAMutQXBYqBeWyowaN86oxf-7Qoi0z-DbKLbOXX3NUE"